/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface RdsButton {
    }
}
declare global {
    interface HTMLRdsButtonElement extends Components.RdsButton, HTMLStencilElement {
    }
    var HTMLRdsButtonElement: {
        prototype: HTMLRdsButtonElement;
        new (): HTMLRdsButtonElement;
    };
    interface HTMLElementTagNameMap {
        "rds-button": HTMLRdsButtonElement;
    }
}
declare namespace LocalJSX {
    interface RdsButton {
    }
    interface IntrinsicElements {
        "rds-button": RdsButton;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "rds-button": LocalJSX.RdsButton & JSXBase.HTMLAttributes<HTMLRdsButtonElement>;
        }
    }
}
